Pass Exercises from SIT720 Machine Learning, Week1 By Marcelo Marsson Goncalves da Costa.

1) Define a string variable with your name. Print characters of odd and even position of your name.
2) (assumption we are using 0 as the starting index and 0 is even)

In [1]:
my_name = "Marcelo Marsson Goncalves da Costa"
even_chars = ""
odd_chars = ""
for i, char in enumerate(my_name):
    if i%2 == 0:
        even_chars = even_chars + char
    else:
        odd_chars = odd_chars + char
print("even chars: "+even_chars)
print("odd chars: "+odd_chars)

even chars: MreoMrsnGnavsd ot
odd chars: acl aso ocle aCsa


2) Create three variables named 'Student name', 'Course name', and 'EmailAddress'. Add 5 random values in these variables, where added values are not replaceable and print them.
#### This question is QUITE confusing. Variable names do not accept spaces in python, and python does not have a constant keyword to avoid them being changed. If the point was using immutable data structures such as tuples, the wording should be different. We should add 5 random values to what exactly? 5 chars to a string? 5 different values to a tuple or dictionary? if so, the naming of the variables is not good as it should indicate that the variable is a list/dic/tuple and not a single record.

In [2]:
import random
import string
student_name = set()
course_name = set()
email_address = set()

# Adding 5 unique/random values to each set
while len(student_name) < 5:
  student_name.add(''.join(random.choice(string.ascii_lowercase) for i in range(5)))

while len(course_name) < 5:
  course_name.add(''.join(random.choice(string.ascii_lowercase) for i in range(5)))

while len(email_address) < 5:
  email_address.add(''.join(random.choice(string.ascii_lowercase) for i in range(5)) + '@marsson.deakin.edu.au')

print('Student Names:', student_name)
print('Course Names:', course_name)
print('Email Addresses:', email_address)

Student Names: {'qctsq', 'kimkl', 'pszqn', 'toewg', 'sdoam'}
Course Names: {'iemcp', 'dyyrj', 'pinvi', 'gdldr', 'dybsf'}
Email Addresses: {'odpoc@marsson.deakin.edu.au', 'eqehg@marsson.deakin.edu.au', 'clgir@marsson.deakin.edu.au', 'uyqjj@marsson.deakin.edu.au', 'lumru@marsson.deakin.edu.au'}


3. Create a dictionary variable with three keys, which are named same as the three variables created in the previous problem. Insert the previously created three variables values in the dictionary variable and print it.

In [3]:
crazy_dictionary = {
    'student_name': student_name,
    'course_name': course_name,
    'email_address': email_address
}

print(crazy_dictionary)

{'student_name': {'qctsq', 'kimkl', 'pszqn', 'toewg', 'sdoam'}, 'course_name': {'iemcp', 'dyyrj', 'pinvi', 'gdldr', 'dybsf'}, 'email_address': {'odpoc@marsson.deakin.edu.au', 'eqehg@marsson.deakin.edu.au', 'clgir@marsson.deakin.edu.au', 'uyqjj@marsson.deakin.edu.au', 'lumru@marsson.deakin.edu.au'}}


4) Define a string variable 'energy' and assign value either 'Fossil' or 'Renewable'. Print "Natural gas" if the value of energy variable is 'Fossil' otherwise print "solar power". What will your program print if energy='Biomass '?
Will print "solar power"

In [4]:
energy = "Biomass "
if energy == "Fossil":
    print("Natural Gas")
else:
    print ("solar power")

solar power


5) Print all prime numbers between 0 and 100 separated by line.
#### As there were no performance requirments, I used the basic recurrent method.

In [5]:
for number in range(2, 101):
    for i in range(2, number):
        if (number % i) == 0:
            break
    else:
        print(number)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


6) Is it possible to break a loop before executing for the defined number of iterations? If yes, provide an example using While loop structure. Otherwise, explain your answer (why and how).
#### Yes it is, by using the break statement

In [6]:
i=0
while True:
    i += 1
    print (i)
    if i == 100:
        break


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


7) Create  functions named  'Addition', 'Multiplication', 'Division' and 'Subtraction'. These functions takes two input parameters say (x, y) and return (x+y),(x*y), (x/y) and (x-y). Call the function with (4,7) arguments and print the outputs

In [7]:
def addition (param_1, param_2):
    return param_1 + param_2

def multiplication (param_1, param_2):
    return param_1 * param_2

def division (param_1, param_2):
    return param_1 / param_2

def subtraction (param_1, param_2):
    return param_1 - param_2

print (addition(4,7))
print (multiplication(4,7))
print (division(4,7))
print (subtraction(4,7))

11
28
0.5714285714285714
-3


8) Create and display a 8x8 Identity matrix and multiply it with a 8x4 Random matrix.
** Identity matrices are matrices where all te items from the main diagonal are 1, and all the other are 0
#### As an assumption will generate a random float matrix to multiply.


In [16]:
import numpy as np
identity = np.identity(8)
random = np.random.rand(8,4);
result_matrix = np.matmul(identity,random)
print (result_matrix)

[[0.36672524 0.98729738 0.54973968 0.92605256]
 [0.68880133 0.52694081 0.53186371 0.69438741]
 [0.16589754 0.71148268 0.02649788 0.71021606]
 [0.8028238  0.52155957 0.17650823 0.23059806]
 [0.54449201 0.56171679 0.03986857 0.97536161]
 [0.11006012 0.89009685 0.9134267  0.36896225]
 [0.31817378 0.26403998 0.98064286 0.24128591]
 [0.82746087 0.13212496 0.47288826 0.4431712 ]]


9) Create a 8x9 matrix, initialise with random values and print it. Now, transpose the matrix and print it. How the transposed matrix is different from original matrix?
##### A transposed matrix has the rows transformed into columns or columns transposed into rows.

In [17]:
eight_by_nine = np.random.rand(8,9)
eight_by_nine_transposed = eight_by_nine.transpose()
print (eight_by_nine)
print (eight_by_nine_transposed)


[[0.14503021 0.58217185 0.90439342 0.37077889 0.79402142 0.13028857
  0.0144397  0.64555203 0.31432158]
 [0.13076799 0.0768405  0.32207679 0.62758618 0.34215225 0.59746121
  0.6590024  0.88226036 0.98747803]
 [0.06930836 0.59897305 0.91340845 0.13708544 0.23616889 0.4445592
  0.82406656 0.8236445  0.21560418]
 [0.63891277 0.69790117 0.62272864 0.90611132 0.62636735 0.20389515
  0.36102132 0.25627109 0.15445934]
 [0.97999422 0.43508122 0.99231934 0.45836375 0.61463041 0.40158766
  0.20732947 0.32460617 0.18667113]
 [0.13189182 0.40747955 0.98865379 0.40588014 0.39208023 0.65721704
  0.9608708  0.63382372 0.12426009]
 [0.12649781 0.56069545 0.27673502 0.83233342 0.31750263 0.01118783
  0.0393445  0.24118114 0.83041941]
 [0.47832266 0.39414084 0.49069846 0.24708354 0.34285115 0.80169282
  0.77752902 0.76612362 0.09233549]]
[[0.14503021 0.13076799 0.06930836 0.63891277 0.97999422 0.13189182
  0.12649781 0.47832266]
 [0.58217185 0.0768405  0.59897305 0.69790117 0.43508122 0.40747955
  0.560

In [18]:
ped_corss_matrix = np.genfromtxt("PedestrianCounting.csv", delimiter="," ,skip_header=1)
ped_corss_matrix_2_copy = ped_corss_matrix[:, 2].copy()
mean = np.mean(ped_corss_matrix_2_copy)
ped_cross_3_minus_mean = ped_corss_matrix_2_copy - mean

print(ped_corss_matrix_2_copy)
print(ped_cross_3_minus_mean)

[ 791. 1301. 1532. ...   34.   57.   48.]
[ 584.28408676 1094.28408676 1325.28408676 ... -172.71591324 -149.71591324
 -158.71591324]
